import { useState } from 'react';
import { supabase } from '../../../lib/supabase';
import api from '../../../lib/api';

// Website Summary State & Handlers
export default function useSiteSummary(activeSite) {
  const [siteSummary, setSiteSummary] = useState('');
  const [isLoadingSummary, setIsLoadingSummary] = useState(true);
  const [isSavingSummary, setIsSavingSummary] = useState(false);
  const [isRegeneratingSummary, setIsRegeneratingSummary] = useState(false);
  const [summarySuccessMsg, setSummarySuccessMsg] = useState('');
  const [showSummaryEditor, setShowSummaryEditor] = useState(false);

  // The widget's opening state (greeting, header labels, input placeholder)
  // — generated by the same AI pass as the business summary, at scan time,
  // but unlike the summary it used to have no review step at all: it went
  // straight from the model's first draft to every visitor's first
  // impression, with the tenant never even seeing what it said. Same fields
  // api/chat/init.js serves live; same table (site_summaries) the summary
  // itself lives in.
  const [welcomeMessage, setWelcomeMessage] = useState('');
  const [uiStatusTitle, setUiStatusTitle] = useState('');
  const [uiStatusOnline, setUiStatusOnline] = useState('');
  const [uiInputPlaceholder, setUiInputPlaceholder] = useState('');
  const [welcomeLanguage, setWelcomeLanguage] = useState('');
  const [hasWelcomeExperience, setHasWelcomeExperience] = useState(false);
  const [isSavingWelcome, setIsSavingWelcome] = useState(false);
  const [welcomeSuccessMsg, setWelcomeSuccessMsg] = useState('');
  const [showWelcomeEditor, setShowWelcomeEditor] = useState(false);

  const applyWelcomeExperience = (row) => {
    setWelcomeMessage(row?.welcome_message || '');
    setUiStatusTitle(row?.ui_status_title || '');
    setUiStatusOnline(row?.ui_status_online || '');
    setUiInputPlaceholder(row?.ui_input_placeholder || '');
    setWelcomeLanguage(row?.language || '');
    setHasWelcomeExperience(Boolean(row?.welcome_message));
  };

  const fetchSiteSummary = async () => {
    if (!activeSite?.id) return;
    setIsLoadingSummary(true);
    try {
      const { data: sumData } = await supabase
        .from('site_summaries')
        .select('summary, welcome_message, ui_status_title, ui_status_online, ui_input_placeholder, language')
        .eq('site_id', activeSite.id)
        .maybeSingle();

      if (sumData?.summary) {
        setSiteSummary(sumData.summary);
        applyWelcomeExperience(sumData);
        setIsLoadingSummary(false);
        return;
      }

      const { data: docData } = await supabase
        .from('documents')
        .select('content')
        .eq('site_id', activeSite.id)
        .ilike('url', '%#site-summary')
        .maybeSingle();

      if (docData?.content) {
        setSiteSummary(docData.content.replace(/^\[SITE_SUMMARY\]\n/, ''));
        setIsLoadingSummary(false);
        return;
      }

      if (activeSite?.domain) {
        setIsRegeneratingSummary(true);
        const summaryRes = await api.crawler.summarize({
          tenant_id: activeSite.tenant_id,
          site_id: activeSite.id,
          url: activeSite.domain
        });

        if (summaryRes.ok && summaryRes.data?.summary) {
          setSiteSummary(summaryRes.data.summary);
          // The regenerate call doesn't echo the welcome-experience fields
          // back (they're generated alongside the summary but live in the
          // same site_summaries row) — one more read picks them up.
          const { data: freshRow } = await supabase
            .from('site_summaries')
            .select('welcome_message, ui_status_title, ui_status_online, ui_input_placeholder, language')
            .eq('site_id', activeSite.id)
            .maybeSingle();
          applyWelcomeExperience(freshRow);
        }
      }
    } catch (err) {
      console.error('[fetchSiteSummary] Error:', err);
    } finally {
      setIsLoadingSummary(false);
      setIsRegeneratingSummary(false);
    }
  };

  const handleSaveSummary = async () => {
    if (!activeSite?.id || !siteSummary.trim()) return;
    setIsSavingSummary(true);
    try {
      await supabase.from('site_summaries').upsert({
        tenant_id: activeSite.tenant_id,
        site_id: activeSite.id,
        summary: siteSummary.trim(),
        updated_at: new Date().toISOString()
      }, { onConflict: 'tenant_id,site_id' });

      // Fallback document sync
      const summaryUrl = `https://${activeSite.domain}#site-summary`;
      await supabase.from('documents').delete().eq('site_id', activeSite.id).eq('url', summaryUrl);
      await supabase.from('documents').insert({
        tenant_id: activeSite.tenant_id,
        site_id: activeSite.id,
        url: summaryUrl,
        content: `[SITE_SUMMARY]\n${siteSummary.trim()}`
      });

      setSummarySuccessMsg('✓ Business summary saved successfully!');
      setTimeout(() => setSummarySuccessMsg(''), 3500);
    } catch (err) {
      console.error('[handleSaveSummary] Error:', err);
    } finally {
      setIsSavingSummary(false);
    }
  };

  const handleRegenerateSummary = async () => {
    if (!activeSite?.id || isRegeneratingSummary) return;
    setIsRegeneratingSummary(true);
    try {
      const res = await api.crawler.summarize({
        tenant_id: activeSite.tenant_id,
        site_id: activeSite.id,
        url: activeSite.domain
      });

      if (res.ok && res.data?.summary) {
        setSiteSummary(res.data.summary);
        setSummarySuccessMsg('✓ AI Business Summary regenerated successfully!');
        setTimeout(() => setSummarySuccessMsg(''), 3500);

        const { data: freshRow } = await supabase
          .from('site_summaries')
          .select('welcome_message, ui_status_title, ui_status_online, ui_input_placeholder, language')
          .eq('site_id', activeSite.id)
          .maybeSingle();
        applyWelcomeExperience(freshRow);
      }
    } catch (err) {
      console.error('[handleRegenerateSummary] Error:', err);
    } finally {
      setIsRegeneratingSummary(false);
    }
  };

  // Lets the owner review and correct what a visitor actually sees before
  // saying anything — the AI's first draft, not silently promoted to "what
  // the widget says" the moment a scan finishes.
  const handleSaveWelcomeExperience = async () => {
    if (!activeSite?.id) return;
    setIsSavingWelcome(true);
    try {
      const { error } = await supabase.from('site_summaries').upsert({
        tenant_id: activeSite.tenant_id,
        site_id: activeSite.id,
        // NOT NULL on this table — a save from this editor always has a
        // summary already loaded, but guard against upserting a blank one.
        summary: siteSummary || 'This business has not been summarized yet.',
        welcome_message: welcomeMessage.trim() || null,
        ui_status_title: uiStatusTitle.trim() || null,
        ui_status_online: uiStatusOnline.trim() || null,
        ui_input_placeholder: uiInputPlaceholder.trim() || null,
        updated_at: new Date().toISOString()
      }, { onConflict: 'tenant_id,site_id' });

      if (error) throw error;

      setHasWelcomeExperience(Boolean(welcomeMessage.trim()));
      setWelcomeSuccessMsg('✓ Widget greeting saved — visitors will see this on their next page load.');
      setTimeout(() => setWelcomeSuccessMsg(''), 3500);
    } catch (err) {
      console.error('[handleSaveWelcomeExperience] Error:', err);
    } finally {
      setIsSavingWelcome(false);
    }
  };

  return {
    siteSummary,
    setSiteSummary,
    isLoadingSummary,
    isSavingSummary,
    isRegeneratingSummary,
    setIsRegeneratingSummary,
    summarySuccessMsg,
    showSummaryEditor,
    setShowSummaryEditor,
    fetchSiteSummary,
    handleSaveSummary,
    handleRegenerateSummary,
    welcomeMessage,
    setWelcomeMessage,
    uiStatusTitle,
    setUiStatusTitle,
    uiStatusOnline,
    setUiStatusOnline,
    uiInputPlaceholder,
    setUiInputPlaceholder,
    welcomeLanguage,
    hasWelcomeExperience,
    isSavingWelcome,
    welcomeSuccessMsg,
    showWelcomeEditor,
    setShowWelcomeEditor,
    handleSaveWelcomeExperience
  };
}
