/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          900: '#0b0f19',
          800: '#111827',
          700: '#1f2937',
          600: '#374151'
        },
        // The full scale here — not just the 3 shades that happened to be
        // used when this was first added — because `brand-200`/`brand-400`/
        // etc. are already used throughout the app (About page gradient
        // text, buttons, badges...); any shade missing from this object is
        // silently not generated by Tailwind, which renders as invisible
        // text or unstyled elements with no build warning. 500/600/700
        // are Tailwind's own `indigo` scale, so the rest is filled in from
        // that same scale for a consistent progression.
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b'
        }
      }
    },
  },
  plugins: [],
}
