// French translations for miscellaneous top-level components (About, payment
// pages, tables, small dialogs). English string → French. Preserve {tokens}.
export default {
  // AboutPage.jsx
  'Pioneering the Future of': "À l'avant-garde de l'avenir des",
  'B2B AI Assistants': 'assistants IA B2B',
  'Point us at your website and, minutes later, an assistant that actually knows your business is live on it — greeting visitors, answering their questions, and following up so no opportunity slips through.':
    "Indiquez-nous l'adresse de votre site et, quelques minutes plus tard, un assistant qui connaît vraiment votre entreprise y est actif — il accueille les visiteurs, répond à leurs questions et fait les suivis pour qu'aucune occasion ne vous échappe.",
  'Live in Minutes': 'En ligne en quelques minutes',
  "No setup, no training, no waiting on a developer. Give us your website's address and your assistant learns it on the spot, ready to chat the moment you hit publish.":
    "Aucune installation, aucune formation, aucune attente pour un développeur. Donnez-nous l'adresse de votre site et votre assistant l'apprend sur-le-champ, prêt à discuter dès que vous publiez.",
  "Speaks Your Visitors' Language": 'Parle la langue de vos visiteurs',
  'Wherever your customers come from, whatever language they type in, your assistant meets them there — no configuration required.':
    "Peu importe d'où viennent vos clients ou la langue dans laquelle ils écrivent, votre assistant s'adapte à eux — aucune configuration requise.",
  'Your Business, Kept Private': 'Votre entreprise, en toute confidentialité',
  'Everything your assistant learns and every conversation it has stays yours alone — completely walled off from every other business on the platform.':
    "Tout ce que votre assistant apprend et chaque conversation qu'il a vous appartiennent exclusivement — complètement isolés de toute autre entreprise sur la plateforme.",
  'More Than a Chat Window': "Plus qu'une simple fenêtre de clavardage",
  "Your assistant does not just answer questions — it captures interested visitors' details, books time on your calendar, and hands off to a human exactly when needed.":
    "Votre assistant ne fait pas que répondre aux questions — il recueille les coordonnées des visiteurs intéressés, réserve du temps dans votre agenda et transfère la conversation à une personne exactement quand il le faut.",
  'Ready to transform your customer experience?': 'Prêt à transformer votre expérience client?',
  'Put an assistant on your site today and start turning visitors into conversations, and conversations into customers.':
    "Mettez un assistant sur votre site dès aujourd'hui et commencez à transformer vos visiteurs en conversations, et vos conversations en clients.",
  'View Pricing Plans': 'Voir les forfaits',

  // ConfigurationError.jsx
  'Configuration requise': 'Configuration requise',

  // LeadsTable.jsx
  'ID': 'ID',
  'Name': 'Nom',
  'Email': 'Courriel',
  'Phone': 'Téléphone',
  'Created Date': 'Date de création',
  'Leads ({n})': 'Prospects ({n})',
  'Visitors who asked to be contacted, or left their details while chatting with your assistant.':
    'Visiteurs qui ont demandé à être contactés, ou qui ont laissé leurs coordonnées en clavardant avec votre assistant.',
  'Search by name, email, or phone...': 'Rechercher par nom, courriel ou téléphone...',
  'Export CSV': 'Exporter en CSV',
  'No leads captured yet. Enable lead capture in your AI settings.':
    "Aucun prospect recueilli pour l'instant. Activez la collecte de prospects dans les paramètres de votre IA.",
  'Unknown Name': 'Nom inconnu',
  'Not provided': 'Non fourni',
  'Inquiry Summary': 'Résumé de la demande',
  'No summary generated by AI.': "Aucun résumé généré par l'IA.",

  // SupportTicketsTable.jsx
  'Support Requests ({n})': "Demandes d'assistance ({n})",
  'Every time a visitor asked your assistant for human help — and whether the email actually reached you.':
    "Chaque fois qu'un visiteur a demandé à votre assistant l'aide d'une personne — et si le courriel vous est bel et bien parvenu.",
  'Search by name, email, or message...': 'Rechercher par nom, courriel ou message...',
  'No support requests yet. They show up here as soon as a visitor asks your assistant for help.':
    "Aucune demande d'assistance pour l'instant. Elles apparaîtront ici dès qu'un visiteur demandera de l'aide à votre assistant.",
  'Unknown visitor': 'Visiteur inconnu',
  'Emailed to you': 'Courriel envoyé',
  'Email failed': 'Échec du courriel',
  'Message': 'Message',
  'No message given.': 'Aucun message fourni.',
  "We couldn't get this into your inbox, so it's kept here instead — you can reply to the visitor directly at the address above. Our team has been notified.":
    "Nous n'avons pas réussi à le livrer dans votre boîte de réception, alors il est conservé ici à la place — vous pouvez répondre directement au visiteur à l'adresse ci-dessus. Notre équipe a été avisée.",

  // PaymentSuccessPage.jsx
  'Welcome to the': 'Bienvenue dans le',
  'Pro Plan! 🎉': 'forfait Pro! 🎉',
  'Your payment was processed successfully. Your subscription is now active.':
    'Votre paiement a été traité avec succès. Votre abonnement est maintenant actif.',
  'All premium features unlocked': 'Toutes les fonctionnalités premium débloquées',
  'Priority customer support active': 'Soutien à la clientèle prioritaire activé',
  'Automatic Stripe invoicing & billing': 'Facturation automatique via Stripe',
  'Go to My Dashboard': 'Accéder à mon tableau de bord',
  'Automatic redirect in a few seconds…': 'Redirection automatique dans quelques secondes…',

  // PlanBadge.jsx
  'Active': 'Actif',
  'Free': 'Gratuit',
  'Trialing': "À l'essai",
  'Past due': 'En retard',
  'Canceled': 'Annulé',
  'Plan {plan} — {status}': 'Forfait {plan} — {status}',

  // WorkspaceTransfer.jsx
  'your guest workspace': 'votre espace de travail invité',
  '{domain} is now part of this account, with its pages and leads.':
    'Le site {domain} fait maintenant partie de ce compte, avec ses pages et ses prospects.',
  '{domain} is already in this account — we opened the one you already had.':
    'Le site {domain} se trouve déjà dans ce compte — nous avons ouvert celui que vous aviez déjà.',
  'Dismiss': 'Fermer',
  'Move {domain} into this account?': 'Transférer {domain} dans ce compte?',
  'You set this assistant up before signing in. We can move the website, its scanned pages and its captured leads into the account you just signed into. Your test conversations stay behind.':
    "Vous avez configuré cet assistant avant de vous connecter. Nous pouvons transférer le site Web, ses pages analysées et ses prospects recueillis vers le compte auquel vous venez de vous connecter. Vos conversations de test ne seront pas transférées.",
  'Moving…': 'Transfert en cours…',
  'Yes, move it over': 'Oui, transférer',
  'No thanks, leave it': 'Non merci, laisser tel quel',
  'Your plan is full': 'Votre forfait est complet',
  '{domain} is ready to move into this account, but the {planName} plan covers {limit} website{plural} and you already have {siteCount}. Nothing has moved yet — we kept it waiting for you.':
    "{domain} est prêt à être transféré dans ce compte, mais le forfait {planName} couvre {limit} site{plural} et vous en avez déjà {siteCount}. Rien n'a encore été transféré — nous l'avons gardé en attente pour vous.",
  'Upgrade and keep both': 'Mettre à niveau et garder les deux',
  'Or replace an existing site': 'Ou remplacer un site existant',
  'No websites to replace in this account.': 'Aucun site à remplacer dans ce compte.',
  'Replace {site} with {domain}': 'Remplacer {site} par {domain}',
  'This permanently deletes': 'Ceci supprime définitivement',
  ': all of its scanned pages, all of its captured leads, and its chat history. This cannot be undone. {domain} then takes its place.':
    " : toutes ses pages analysées, tous ses prospects recueillis et son historique de conversations. Cette action est irréversible. {domain} prendra alors sa place.",
  'Working…': 'Traitement en cours…',
  'Delete {site} permanently': 'Supprimer {site} définitivement',
  'Cancel': 'Annuler',
  'Decide later': 'Décider plus tard',
};
