import React from 'react';
import { MessageCircle, Edit3, Save, Sparkles } from 'lucide-react';

/** What a visitor actually sees before they say anything: the widget's
 *  opening message and header labels.
 *
 *  Generated by AI at scan time, same as the business summary — but unlike
 *  the summary, it used to have no review step at all: it went straight from
 *  the model's first draft to every visitor's first impression, with the
 *  tenant never even seeing what it said until a visitor mentioned it. This
 *  card is that missing review step: an AI-drafted inference, plainly
 *  labeled as such, that stays a draft until the owner confirms or edits it.
 */
export default function WelcomeExperienceCard({
  welcomeMessage,
  setWelcomeMessage,
  uiStatusTitle,
  setUiStatusTitle,
  uiStatusOnline,
  setUiStatusOnline,
  uiInputPlaceholder,
  setUiInputPlaceholder,
  welcomeLanguage,
  hasWelcomeExperience,
  isSavingWelcome,
  welcomeSuccessMsg,
  showWelcomeEditor,
  setShowWelcomeEditor,
  onSave
}) {
  return (
    <div className="bg-surface-100 p-5 sm:p-6 rounded-xl border border-dark-900/5 space-y-4">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-3 flex-wrap">
            <h4 className="text-sm font-bold text-dark-900 flex items-center gap-2">
              <MessageCircle className="w-4 h-4 text-brand-600" /> What visitors see first
            </h4>
            <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-amber-500/10 text-amber-700 border border-amber-500/20">
              <Sparkles className="w-3 h-3" /> AI draft{welcomeLanguage ? ` · ${welcomeLanguage.toUpperCase()}` : ''}
            </span>
          </div>
          <p className="text-xs text-gray-500 mt-1">
            {hasWelcomeExperience
              ? "The greeting and labels below are what your widget currently shows, before a visitor types anything. Written by AI from your website — read it over and fix anything that's off."
              : 'Not generated yet — regenerate your business summary above to have Dorafi draft these.'}
          </p>
        </div>

        {hasWelcomeExperience && (
          <button
            onClick={() => setShowWelcomeEditor(!showWelcomeEditor)}
            className="text-xs font-semibold text-brand-700 bg-brand-500/10 px-3.5 py-1.5 rounded-lg border border-brand-500/20 hover:bg-brand-500/20 transition-all flex items-center gap-1.5 shrink-0"
          >
            <Edit3 className="w-3.5 h-3.5" />
            {showWelcomeEditor ? 'Collapse' : 'Review / Edit'}
          </button>
        )}
      </div>

      {welcomeSuccessMsg && (
        <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-xs font-medium text-emerald-700 flex items-center gap-2 animate-in fade-in">
          <span>{welcomeSuccessMsg}</span>
        </div>
      )}

      {hasWelcomeExperience && showWelcomeEditor && (
        <div className="pt-3 border-t border-dark-900/5 space-y-4">
          <div>
            <label className="text-xs font-semibold text-gray-500 mb-1 block">Opening message</label>
            <textarea
              rows={2}
              value={welcomeMessage}
              onChange={(e) => setWelcomeMessage(e.target.value)}
              placeholder="Hello! How can I help you today?"
              className="w-full bg-white border border-gray-300 text-dark-900 text-sm rounded-lg px-4 py-2.5 outline-none focus:border-brand-500/50"
            />
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <div className="flex-1">
              <label className="text-xs font-semibold text-gray-500 mb-1 block">Header title</label>
              <input
                type="text"
                value={uiStatusTitle}
                onChange={(e) => setUiStatusTitle(e.target.value)}
                placeholder="Virtual Assistant"
                className="w-full bg-white border border-gray-300 text-dark-900 text-sm rounded-lg px-4 py-2.5 outline-none focus:border-brand-500/50"
              />
            </div>
            <div className="flex-1">
              <label className="text-xs font-semibold text-gray-500 mb-1 block">Status line</label>
              <input
                type="text"
                value={uiStatusOnline}
                onChange={(e) => setUiStatusOnline(e.target.value)}
                placeholder="Online"
                className="w-full bg-white border border-gray-300 text-dark-900 text-sm rounded-lg px-4 py-2.5 outline-none focus:border-brand-500/50"
              />
            </div>
            <div className="flex-1">
              <label className="text-xs font-semibold text-gray-500 mb-1 block">Input placeholder</label>
              <input
                type="text"
                value={uiInputPlaceholder}
                onChange={(e) => setUiInputPlaceholder(e.target.value)}
                placeholder="Ask a question..."
                className="w-full bg-white border border-gray-300 text-dark-900 text-sm rounded-lg px-4 py-2.5 outline-none focus:border-brand-500/50"
              />
            </div>
          </div>

          <div className="flex justify-end">
            <button
              disabled={isSavingWelcome}
              onClick={onSave}
              className="w-full sm:w-auto bg-emerald-600 hover:bg-emerald-500 text-white px-5 py-2 rounded-xl text-xs font-semibold flex items-center justify-center gap-2 transition-all shadow-md disabled:opacity-50"
            >
              <Save className="w-3.5 h-3.5" />
              {isSavingWelcome ? 'Saving...' : 'Save'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
